[package]
name = "lga"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25"
file-format = "0.17.3"
# imghdr = "0.7.0"
tui = "0.19.0"
